### ISSUE TITLE
PBI 4

### ISSUE THREAD

**Issue by spindev** [xpirit-training/demo-features-projects#14]
```[tasklist]
### Tasks
- [ ] https://github.com/xpirit-training/demo-features-projects/issues/20
- [ ] https://github.com/xpirit-training/demo-features-projects/issues/21
- [ ] https://github.com/xpirit-training/demo-features-projects/issues/22
```
